# HTTP Server
server:  
  port: 8057   # HTTP port
 
# Spring properties
spring:  
  application:
    name: arquitect
 
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# Zuul Routes    
zuul:
  routes:
    greetings:
      path: /arquitecto/**
      serviceId: ARQUITECTO
      stripPrefix: false
